//! L1 — raw, unsafe FFI bindings to the [ps5-payload-sdk] C API.
//!
//! This crate is the bottom layer of the payload. It exposes the SDK's
//! `extern "C"` functions and types verbatim — every item is `unsafe` to call
//! and maps 1:1 to the C symbol. It is `no_std` and contains no abstraction.
//!
//! Most bindings are generated by `bindgen` from the SDK headers (see
//! `build.rs`); the HTTP/TLS surface has no SDK headers and is hand-written.
//!
//! Build higher layers on top, never call this directly from application code:
//!   - **L2** (`ps5`)  — safe, idiomatic wrappers (RAII, `Result`, slices).
//!   - **L3** (`core`) — business-core use cases.
//!   - **L4** (`app`)  — the application feature linked into the `.elf`.
//!
//! ## Layout
//! - crate root — the `ps5/*` kernel API (`payload_*`, `kernel_*`, `klog_*`,
//!   `mdbg_*`, `nid_*`, `KERNEL_*`) plus `errno` codes, [`__error`], [`strerror`].
//! - [`fs`]     — POSIX/BSD file & filesystem (feature `fs`).
//! - [`net`]    — BSD sockets (feature `net`).
//! - [`thread`] — pthread / semaphore / sched / C11 threads (feature `thread`).
//! - [`sce`]    — Sony SceHttp2 / SceSsl / SceNet FFI, hand-written (feature `http`).
//!
//! ## Linkage
//! The `ps5/*` symbols come from `crt1.o`; POSIX/BSD and C-library symbols from
//! `kernel_web` / `SceLibcInternal` / the SDK `libc.a` (all default-linked by
//! `prospero-clang`). The `http` feature additionally requests `-lSceHttp2
//! -lSceSsl` at the final link. See `docs/SDK_API_INVENTORY.md`.
//!
//! [ps5-payload-sdk]: https://github.com/ps5-payload-dev/sdk
#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
// Bindgen output is raw FFI; these lints are noise for generated code.
#![allow(clippy::all)]

// Core surface (ps5/* + errno + strerror), always present, at the crate root.
include!(concat!(env!("OUT_DIR"), "/ps5_bindings.rs"));

#[cfg(feature = "fs")]
pub mod fs {
    //! POSIX/BSD file & filesystem FFI (generated from `headers/fs.h`).
    include!(concat!(env!("OUT_DIR"), "/fs_bindings.rs"));
}

#[cfg(feature = "net")]
pub mod net {
    //! BSD socket FFI (generated from `headers/net.h`).
    include!(concat!(env!("OUT_DIR"), "/net_bindings.rs"));
}

#[cfg(feature = "thread")]
pub mod thread {
    //! pthread / semaphore / sched / C11-thread FFI (generated from `headers/thread.h`).
    include!(concat!(env!("OUT_DIR"), "/thread_bindings.rs"));
}

#[cfg(feature = "http")]
pub mod sce;
